config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'books#index'

  resources :books do
    resources :reviews, only: [:create, :edit, :update, :new, :destroy] do
    resources :users, only: [:show, :index]
  end
  end

  resources :profile_pages, only: [:show, :index]

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  validates :title, length: {minimum: 1}
  validates :description, length: {minimum: 10}
  validates :url, presence: true
end

app/models/profilepage.rb
class ProfilePage < ActiveRecord::Base
  has_many :users
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  has_many :users, through: :book
  validates :description, length: {minimum: 50}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :reviews, through: :books
  belongs_to :profile_pages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:digitalocean]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

  helpers do
    def current_user
      user_id = session[:user_id]
      @current_user ||= User.find(user_id) if user_id.present?
    end

    def signed_in?
      current_user.present?
    end
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end

  def index
    @users = User.all
    @books = Book.order('created_at')
  end

  def show
    @book = Book.find(params[:id])
    @reviews = Review.order('created_at').where(book_id: @book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Your book was removed."
  end

  def new
    @books = Book.new
  end

  def create
    @books = Book.new(book_params)
    @books.user_id = current_user.id
    if @books.save
      redirect_to books_path(@books), notice: "Book Submitted"
    else
      flash.now[:notice]= @books.errors.full_messages
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    redirect_to @book
  end

  def book_params
    params.require(:book).permit(:title, :url, :description, :user_id)
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def digitalocean
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/profile_pages_controller.rb
class ProfilePagesController < ApplicationController
  helpers do
    def current_user
      user_id = session[:user_id]
      @current_user ||= User.find(user_id) if user_id.present?
    end

    def signed_in?
      current_user.present?
    end
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end

  def astronaut
    current_user.astronaut = true
  end

  def candidate
    current_user.astronaut = false
  end

  def index
  end

  def show
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :authenticate_user!

  helpers do
    def current_user
      user_id = session[:user_id]
      @current_user ||= User.find(user_id) if user_id.present?
    end

    def signed_in?
      current_user.present?
    end
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end

  def create
    @users = User.all
    @book = Book.find(params[:book_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.book_id = @book.id

    if @review.save
    redirect_to book_path(id: @book.id), notice: "Your Review was submitted."
    else
    redirect_to :back, notice: "Your Review must be longer than 50 chars."
    end
  end

  def new
    @users = User.all
    @book = Book.find(params[:book_id])
    @reviews = Review.new
  end

  def destroy
    @review = Review.find(params[:id])
    @book = Book.find(params[:book_id])
    @review.destroy
    redirect_to book_path(id: @book.id), notice: "Your Review was terminated."
  end

  def edit
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
  end

  def update
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
    @review.update_attributes(review_params)
    redirect_to book_path(id: @book.id), notice: "Your Review was editted"
  end

  private

  # def find_params
  #   @review = Review.find(params[:id])
  # end

  def review_params
    params.require(:review).permit(:description, :book_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/profile_pages_helper.rb
module ProfilePagesHelper
end

app/helpers/profilepage_helper.rb
module ProfilepageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h1>Them books</h1>
<div>
<%= link_to "Profile Page", profile_pages_path%>
</div>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <li>
        <%= flash[:notice]%>
      </li>
        <br>
    </div>
  </div>
<%end%>

<div>
  <br>
    <%= link_to "Submit a Book", new_book_path%>
  <br>
  </br>
</div>
<%if @books%>
  <% @books.each do |q| %>
    <div class = "field">
      <%= "Book: " %>
        <%= link_to q.title, book_path(q) %>
    </div>
    <div>
      <%= "Description: " %>
      <li><%= q.description %></li>
      <%= link_to "#{q.url}", "http://#{q.url}" %>
    </div>
      <%if q.user.astronaut == true %>
        <%="Made by an astronaut."%>
      <%else%>
        <%="Made by a candidate."%>
      <%end%>
    <br>
      <%if current_user.id == q.user.id%>
        <%= form_for q, method: :delete do |f| %>
          <%= f.submit "Delete Book" %>
        <%end%>
      <%end%>
    </br>
  <%end%>
<%end%>

app/views/books/new.html.erb
<h1><%= "Submission" %></h1>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <li>
        <%= flash[:notice]%>
      </li>
    </div>
  </div>
<% end %>

<br>
  <%= form_for @books do |f| %>
    <div>
      <%= f. label :title%>
      <br>
        <%= f. text_area :title%>
    </div>
    <div>
      <%= f. label :description %>
      <br>
        <%= f. text_area :description, size: "40x10" %>
    </div>
    <div>
      <%= f. label :url%>
      <br>
        <%= f. text_area :url%>
    </div>
    <div>
      <%= f.submit  "Submit"%>
    <div>
  <%end%>
</br>

app/views/books/show.html.erb
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <li>
        <%=flash[:notice]%>
      </li>
    </div>
  </div>
<% end %>

<h1>
  <%=@book.title %>
</h1>
<h2><%="Submitted by: " %>
<%=@book.user.email%>
</h2>
  <%=link_to "Review the book", new_book_review_path(book_id: params[:id])%>
<div>&nbsp;</div>

<body>

<%=@book.description%>

    <%if @reviews%>
      <%@reviews.each do |a|%>
      <div>&nbsp;</div>
      <li><%="Review: "%><%=a.description%></li>

    <div>
      <%if a.book.user.astronaut == true %>
        <%="Posted by an astronaut"%>
      <%else%>
        <%="Posted by a candidate"%>
      <%end%>
    </div>

        <%if current_user.id == a.user_id%>
         <%=link_to "Edit Review", edit_book_review_path(book_id: @book.id, id: a.id)%>
          <%= form_for [@book, a], method: :delete do |r| %>
            <%= r.submit "Delete Review"%>
          <%end%>
        <%end%>
      <%end%>
    <%end%>

  <div>&nbsp;</div>
    <%=link_to "Go Back", books_path%>
  <div>&nbsp;</div>
    <%if "#{current_user.id}" == "#{@book.user_id}"%>
      <%= form_for @book, method: :delete do |f| %>
        <%= f.submit "Delete Book" %>
      <%end%>
    <%end%>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReviewsInSpace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profile_pages/index.html.erb
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <li>
        <%=flash[:notice]%>
      </li>
    </div>
  </div>
<% end %>
<div>
<%="Welcome " + "#{current_user.email} !" %>
</div>
<%= link_to "Edit profile", "users/edit" %>
<br>
</br>
<div>
  <%if current_user.astronaut == true%>
    <%="You are an astronaut do you want to want to be an candidate?"%>
      <%= link_to "LAND", profile_page_path(2) %>
  <%else%>
    <%="You are a candidate do you want to want to be an astronaut?"%>
      <%= link_to "LAUNCH", profile_page_path(1) %>
  <%end%>
</div>

app/views/profile_pages/show.html.erb
<%#current_user.save%>

<%if current_user.astronaut == true%>
<%current_user.astronaut = false%>
<%current_user.save%>
<h1><%="You have landed."%></h1>
<%else%>
<%current_user.astronaut = true%>
<%current_user.save%>
<h1><%="You have launched!"%></h1>
<%end%>

<%=link_to "Home", books_path%>

app/views/reviews/edit.html.erb
<body>
  <%= form_for [@book, @review], method: :patch do |f| %>
    <div>
      <%= f. label :description %>
    </div>
        <%= f. text_area :description, size: "40x10" %>
    <div>
      <%= f.submit  "Submit", :name => "edit" %>
    </div>
  <%end%>
</body>
<br>

<%= form_for [@book, @review], method: :delete do |r| %>
  <%= r.submit "Delete Review", :name => "delete" %>
<%end%>


<%#=link_to "Go Back", book_path(id: @book.id)%>

app/views/reviews/new.html.erb
<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <li>
        <%= flash[:notice]%>
      </li>
    </div>
  </div>
<% end %>

<div>&nbsp;</div>
  <%= form_for [@book, @reviews] do |z| %>
    <div>
      <%= z.label :description%>
      <div>&nbsp;</div>
      <%= z.text_area :description, :size=> "20x10"%>
    </div>
     <div>
      <%= "Posting as: "%>
      <%=current_user.email%>
    </div>
    <div>
      <%= z.submit  "Submit"%>
    <div>
  <%end%>
</br>

<%=link_to "Go Back", book_path(id: @book.id)%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>